#opcodes
C_MSG_ADD_TO_LEADEBOARD           = 1
S_MSG_ADD_TO_LEADEBOARD           = 2
C_MSG_GET_LEADERBOARD             = 3
S_MSG_GET_LEADERBOARD             = 4
C_MSG_GET_EMERGENCY_SCREEN_DATA   = 5
S_MSG_GET_EMERGENCY_SCREEN_DATA   = 6
C_MSG_GET_DAILY_CHALLENGE         = 7
S_MSG_GET_DAILY_CHALLENGE         = 8
