#opcodes
C_MSG_ADD_TO_LEADEBOARD           = 1
S_MSG_ADD_TO_LEADEBOARD           = 2
C_MSG_GET_LEADERBOARD             = 3
S_MSG_GET_LEADERBOARD             = 4
C_MSG_GET_EMERGENCY_SCREEN_DATA   = 5
S_MSG_GET_EMERGENCY_SCREEN_DATA   = 6
C_MSG_GET_DAILY_CHALLENGE         = 7
S_MSG_GET_DAILY_CHALLENGE         = 8

#used x keys
X_KEY_FOR_LEADERBOARDS_MIN  = 1
X_KEY_FOR_LEADERBOARDS_MAX  = 65535
X_KEY_FOR_SETTINGS          = 100000
X_KEY_FOR_STATS             = 200000

#used y keys
SETTINGS_Y_KEY_EMERGENCY_SCREEN                 = 1
SETTINGS_Y_KEY_GAME_IDS                         = 2 #unused
SETTINGS_Y_DAILY_CHALLENGE_LEVELS               = 3
SETTINGS_Y_DAILY_CHALLENGE_ACTIVE_LEVELS        = 4
SETTINGS_Y_DAILY_CHALLENGE_LAST_ACTIVE_LEVEL    = 5
SETTINGS_Y_DAILY_CHALLENGE_OPCODE_STATS         = 10
SETTINGS_Y_KEY_EMERGENCY_SCREEN_LUA             = 100